<a href="https://colab.research.google.com/github/ykitaguchi77/statistics_for_articles/blob/main/Refractive_change_blepharoptosis_surgery.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Refractive change in blepharoptosis surgery**

In [70]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [97]:
import pandas as pd
pd.set_option('display.max_columns', 300)
pd.set_option('display.max_rows', 300)

In [ ]:
import pandas as pd

xlsx_path = "/content/drive/MyDrive/研究/進行中の研究/眼瞼下垂手術による屈折変化/眼瞼下垂.xlsx"

data = pd.read_excel(xlsx_path, header=1)

# Display the first few rows of the dataframe and its columns to understand its structure
data

In [ ]:
# Step 1: Filter rows where surgery is bilateral (手術側 == 'B')
bilateral_cases = data[data['手術側'] == 'B'].copy()
unilateral_cases = data[data['手術側'] != 'B'].copy()
unilateral_right_cases = data[data['手術側'] == 'R'].copy()
unilateral_left_cases = data[data['手術側'] == 'L'].copy()
print(f"Number of bilateral cases: {len(bilateral_cases)}")
print(f"Number of unilateral cases: {len(unilateral_cases)}")

# Step 2: Duplicate these rows for 'R' and 'L'
bilateral_right_cases = bilateral_cases.copy()
bilateral_left_cases = bilateral_cases.copy()

# Assign 'R' and 'L' to the new surgery side columns
bilateral_right_cases.loc[:, '手術側'] = 'R'
bilateral_left_cases.loc[:, '手術側'] = 'L'

# Step 3: Concatenate the modified bilateral and unilateral cases
right_cases = pd.concat([bilateral_right_cases, unilateral_right_cases])
left_cases = pd.concat([bilateral_left_cases, unilateral_left_cases])

# Step 3: Rename and reallocate columns containing 'R' or 'L' for bilateral cases
for column in right_cases.columns:
    if ' R' in column:
        # Extract the base column name without ' R'
        new_column_name = column.replace(' R', '')
        # Copy data to a new column without side specification
        right_cases.loc[:, new_column_name] = right_cases[column]
        # Drop the original ' R' column
        right_cases.drop(column, axis=1, inplace=True)
    elif ' L' in column:
        # # Extract the base column name without ' L'
        # new_column_name = column.replace(' L', '')
        # # Copy data to a new column without side specification
        # right_cases.loc[:, new_column_name] = right_cases[column]
        # Drop the original ' L' column
        right_cases.drop(column, axis=1, inplace=True)

for column in left_cases.columns:
    if ' R' in column:
        # # Extract the base column name without ' R'
        # new_column_name = column.replace(' R', '')
        # # Copy data to a new column without side specification
        # left_cases.loc[:, new_column_name] = left_cases[column]
        # # Drop the original ' R' column
        left_cases.drop(column, axis=1, inplace=True)
    elif ' L' in column:
        # Extract the base column name without ' L'
        new_column_name = column.replace(' L', '')
        # Copy data to a new column without side specification
        left_cases.loc[:, new_column_name] = left_cases[column]
        # Drop the original ' L' column
        left_cases.drop(column, axis=1, inplace=True)

# Combine the duplicated rows back into a single dataframe
final_df = pd.concat([right_cases, left_cases])
final_df = final_df.sort_values(by='ID').reset_index(drop=True)
# ソート後のデータフレームを表示して確認
#final_df

#final_df.to_excel('output.xlsx', index=False)


In [ ]:
try:
    # Copy values from '波面4M' and '波面post' to '波面3M'
    final_df['波面3M'] = final_df[['波面3M', '波面4M', '波面post']].bfill(axis=1).iloc[:, 0]

    # Drop the columns '波面4M' and '波面post'
    final_df.drop(columns=['波面4M', '波面post'], inplace=True)
    print("波面3M updated!")
except:
    pass

try:
    # Copy values from '波面4M' and '波面post' to '波面3M'
    final_df['AveK 3M'] = final_df[['AveK 3M', 'AveK post']].bfill(axis=1).iloc[:, 0]

    # Drop the columns '波面4M' and '波面post'
    final_df.drop(columns=['AveK post'], inplace=True)
    print("AveK 3M updated!")
except:
    pass

try:
    # Copy values from '波面4M' and '波面post' to '波面3M'
    final_df['CYL 3M'] = final_df[['CYL 3M', 'CYL post']].bfill(axis=1).iloc[:, 0]

    # Drop the columns '波面4M' and '波面post'
    final_df.drop(columns=['CYL post'], inplace=True)
    print("CYL 3M updated!")
except:
    pass

try:
    # Copy values from '波面4M' and '波面post' to '波面3M'
    final_df['angle 3M'] = final_df[['angle 3M', 'angle post']].bfill(axis=1).iloc[:, 0]

    # Drop the columns '波面4M' and '波面post'
    final_df.drop(columns=['angle post'], inplace=True)
    print("angle 3M updated!")
except:
    pass

try:
    # Copy values from '波面4M' and '波面post' to '波面3M'
    final_df['angle 3M'] = final_df[['angle 3M', 'angle post']].bfill(axis=1).iloc[:, 0]

    # Drop the columns '波面4M' and '波面post'
    final_df.drop(columns=['angle post'], inplace=True)
    print("angle 3M updated!")
except:
    pass

try:
    # Copy values from '波面4M' and '波面post' to '波面3M'
    final_df['angle 3M'] = final_df[['angle 3M', 'angle post']].bfill(axis=1).iloc[:, 0]

    # Drop the columns '波面4M' and '波面post'
    final_df.drop(columns=['angle post'], inplace=True)
    print("angle 3M updated!")
except:
    pass

try:
    # Copy values from '波面4M' and '波面post' to '波面3M'
    final_df['angle 3M'] = final_df[['angle 3M', 'angle post']].bfill(axis=1).iloc[:, 0]

    # Drop the columns '波面4M' and '波面post'
    final_df.drop(columns=['angle post'], inplace=True)
    print("angle 3M updated!")
except:
    pass


In [ ]:
# レフケラの欠損値を削除：Drop rows with missing values only in specified columns
specified_columns = ['AveK pre', 'AveK 3M', 'CYL pre', 'CYL 3M', 'angle pre', 'angle 3M', 'MRD-1 pre', 'MRD-1 3M']
final_df = final_df.dropna(subset=specified_columns).reset_index(drop=True)

# SPKの有無を数字に置換
final_df["SPK pre"] = final_df["SPK pre"].replace({"あり": 1, "なし": 0})
final_df["SPK post"] = final_df["SPK post"].replace({"あり": 1, "なし": 0})
# 57行目の"MRD-1 pre"列の値を0.5に置換
final_df.at[57, "MRD-1 pre"] = 0.5

# 挙筋機能"good"のカラムを10に置換
final_df["挙筋機能 pre"] = final_df["挙筋機能 pre"].replace("good", 10)

# "MRD-1 3M"列と"挙筋機能 pre"列をfloat型に変換
final_df["MRD-1 pre"] = final_df["MRD-1 pre"].astype(float)
final_df["MRD-1 3M"] = final_df["MRD-1 3M"].astype(float)
final_df["挙筋機能 pre"] = final_df["挙筋機能 pre"].astype(float)

final_df["sex"] = final_df["sex"].replace({"M": 1, "F": 0})
final_df["手術側"] = final_df["手術側"].replace({"L": 1, "R": 0})

final_df

In [123]:
final_df.to_excel('output.xlsx', index=False)


# **Preprocessed_dataを用いて解析**

In [124]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [125]:
import pandas as pd
pd.set_option('display.max_columns', 300)
pd.set_option('display.max_rows', 300)

In [ ]:
import pandas as pd

xlsx_path = "/content/drive/MyDrive/研究/進行中の研究/眼瞼下垂手術による屈折変化/眼瞼下垂_proprocessed.xlsx"

data = pd.read_excel(xlsx_path, header=0)

# Display the first few rows of the dataframe and its columns to understand its structure
data.head()

##**Linear regression analysis**

In [136]:
from sklearn.linear_model import LinearRegression
import numpy as np

# Prepare the dataset for linear regression analysis
features = data[['age', 'sex', '手術側', 'asg_0_pre', 'asg_45_pre', 'MRD-1 pre', 'MRD-1 3M', '挙筋機能 pre']].dropna()
target_delta_asg_0 = data.loc[features.index, 'Δasg_0']
target_delta_asg_45 = data.loc[features.index, 'Δasg_45']

# Initialize and fit the linear regression model for Δasg_0
model_delta_asg_0 = LinearRegression()
model_delta_asg_0.fit(features, target_delta_asg_0)
coefficients_delta_asg_0 = model_delta_asg_0.coef_
intercept_delta_asg_0 = model_delta_asg_0.intercept_

# Initialize and fit the linear regression model for Δasg_45
model_delta_asg_45 = LinearRegression()
model_delta_asg_45.fit(features, target_delta_asg_45)
coefficients_delta_asg_45 = model_delta_asg_45.coef_
intercept_delta_asg_45 = model_delta_asg_45.intercept_

# Show the results
coefficients_delta_asg_0, intercept_delta_asg_0, coefficients_delta_asg_45, intercept_delta_asg_45


(array([-0.00605295,  0.05506462,  0.05506462, -0.24292907,  0.09596302,
         0.03280512, -0.03908263, -0.02501298]),
 0.9478341482471457,
 array([-0.00177763, -0.0694717 , -0.0694717 ,  0.04678612, -0.47774628,
        -0.05091311, -0.0148833 , -0.00805819]),
 0.3029214671833334)

In [138]:
from sklearn.feature_selection import f_regression

# Calculate p-values for both models
p_values_delta_asg_0 = f_regression(features, target_delta_asg_0)[1]
p_values_delta_asg_45 = f_regression(features, target_delta_asg_45)[1]

p_values_delta_asg_0, p_values_delta_asg_45


(array([7.96460806e-02, 4.67203463e-01, 4.67203463e-01, 5.83804838e-08,
        6.85150742e-01, 4.66708849e-01, 9.97209203e-01, 1.21682678e-01]),
 array([5.61570861e-01, 8.43617019e-01, 8.43617019e-01, 9.95111437e-01,
        1.48893741e-12, 2.65766276e-01, 9.19529483e-01, 5.19321704e-01]))

In [ ]:
import pandas as pd

# Creating a DataFrame to display coefficients and p-values for Δasg_0 and Δasg_45

# Coefficients and intercepts
coeffs_delta_asg_0 = pd.Series(coefficients_delta_asg_0, index=features.columns, name='Coefficients Δasg_0')
coeffs_delta_asg_45 = pd.Series(coefficients_delta_asg_45, index=features.columns, name='Coefficients Δasg_45')
intercept_delta_asg_0 = pd.Series([intercept_delta_asg_0], index=['Intercept'], name='Coefficients Δasg_0')
intercept_delta_asg_45 = pd.Series([intercept_delta_asg_45], index=['Intercept'], name='Coefficients Δasg_45')

# p-values
p_values_delta_asg_0 = pd.Series(p_values_delta_asg_0, index=features.columns, name='p-values Δasg_0')
p_values_delta_asg_45 = pd.Series(p_values_delta_asg_45, index=features.columns, name='p-values Δasg_45')

# Combine all data into one DataFrame for each target
results_delta_asg_0 = pd.concat([intercept_delta_asg_0, coeffs_delta_asg_0, p_values_delta_asg_0], axis=1)
results_delta_asg_45 = pd.concat([intercept_delta_asg_45, coeffs_delta_asg_45, p_values_delta_asg_45], axis=1)

# Combine results into one DataFrame for easy display
results = pd.concat([results_delta_asg_0, results_delta_asg_45], axis=1)
results


In [140]:
# Formatting the DataFrame to display p-values with decimal points
results_formatted = results.copy()

# Formatting p-values for better readability
results_formatted['p-values Δasg_0'] = results['p-values Δasg_0'].map('{:.4f}'.format)
results_formatted['p-values Δasg_45'] = results['p-values Δasg_45'].map('{:.4f}'.format)

results_formatted


Coefficients Δasg_0  \
Intercept   Intercept    0.947834
Name: Coefficients Δasg_...   
age                                                       NaN   
sex                                                       NaN   
手術側                                                       NaN   
asg_0_pre                                                 NaN   
asg_45_pre                                                NaN   
MRD-1 pre                                                 NaN   
MRD-1 3M                                                  NaN   
挙筋機能 pre                                                  NaN   

            Coefficients Δasg_0 p-values Δasg_0  \
Intercept                   NaN             nan   
age                   -0.006053          0.0796   
sex                    0.055065          0.4672   
手術側                    0.055065          0.4672   
asg_0_pre             -0.242929          0.0000   
asg_45_pre             0.095963          0.6852   
MRD-1 pre              0.032805          0.4667   
MRD-1 3M              -0.039083          0.9972   
挙筋機能 pre              -0.025013          0.1217   

                                         Coefficients Δasg_45  \
Intercept   Intercept    0.302921
Name: Coefficients Δasg_...   
age                                                       NaN   
sex                                                       NaN   
手術側                                                       NaN   
asg_0_pre                                                 NaN   
asg_45_pre                                                NaN   
MRD-1 pre                                                 NaN   
MRD-1 3M                                                  NaN   
挙筋機能 pre                                                  NaN   

            Coefficients Δasg_45 p-values Δasg_45  
Intercept                    NaN              nan  
age                    -0.001778           0.5616  
sex                    -0.069472           0.8436  
手術側                    -0.069472           0.8436  
asg_0_pre               0.046786           0.9951  
asg_45_pre             -0.477746           0.0000  
MRD-1 pre              -0.050913           0.2658  
MRD-1 3M               -0.014883           0.9195  
挙筋機能 pre               -0.008058           0.5193

##**線形回帰モデルのAIC（赤池情報量基準）を用いた多変量解析**

In [141]:
import statsmodels.api as sm

# Define the independent variables for the model
X = features
# Add a constant to the model (the intercept)
X = sm.add_constant(X)

# Define the dependent variable for Δasg_0
y_delta_asg_0 = target_delta_asg_0

# Fit the model
model_delta_asg_0 = sm.OLS(y_delta_asg_0, X).fit()

# Define the dependent variable for Δasg_45
y_delta_asg_45 = target_delta_asg_45

# Fit the model
model_delta_asg_45 = sm.OLS(y_delta_asg_45, X).fit()

# Get AIC values
aic_delta_asg_0 = model_delta_asg_0.aic
aic_delta_asg_45 = model_delta_asg_45.aic

aic_delta_asg_0, aic_delta_asg_45, model_delta_asg_0.summary(), model_delta_asg_45.summary()


(395.4150710300904,
 346.91017444446913,
 <class 'statsmodels.iolib.summary.Summary'>
 """
                             OLS Regression Results                            
 Dep. Variable:                 Δasg_0   R-squared:                       0.172
 Model:                            OLS   Adj. R-squared:                  0.140
 Method:                 Least Squares   F-statistic:                     5.367
 Date:                Sun, 12 May 2024   Prob (F-statistic):           1.33e-05
 Time:                        15:47:10   Log-Likelihood:                -189.71
 No. Observations:                 189   AIC:                             395.4
 Df Residuals:                     181   BIC:                             421.3
 Df Model:                           7                                         
 Covariance Type:            nonrobust                                         
                  coef    std err          t      P>|t|      [0.025      0.975]
 ----------------------------

##**Random forest analysis**

In [144]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

# Prepare data
X_train, X_test, y_train_delta_asg_0, y_test_delta_asg_0 = train_test_split(X, y_delta_asg_0, test_size=0.2, random_state=42)
X_train, X_test, y_train_delta_asg_45, y_test_delta_asg_45 = train_test_split(X, y_delta_asg_45, test_size=0.2, random_state=42)

# Initialize and fit the Random Forest model for Δasg_0
rf_model_delta_asg_0 = RandomForestRegressor(n_estimators=100, random_state=42)
rf_model_delta_asg_0.fit(X_train, y_train_delta_asg_0)

# Predictions and evaluation for Δasg_0
predictions_delta_asg_0 = rf_model_delta_asg_0.predict(X_test)
mse_delta_asg_0 = mean_squared_error(y_test_delta_asg_0, predictions_delta_asg_0)
r2_delta_asg_0 = r2_score(y_test_delta_asg_0, predictions_delta_asg_0)

# Initialize and fit the Random Forest model for Δasg_45
rf_model_delta_asg_45 = RandomForestRegressor(n_estimators=100, random_state=42)
rf_model_delta_asg_45.fit(X_train, y_train_delta_asg_45)

# Predictions and evaluation for Δasg_45
predictions_delta_asg_45 = rf_model_delta_asg_45.predict(X_test)
mse_delta_asg_45 = mean_squared_error(y_test_delta_asg_45, predictions_delta_asg_45)
r2_delta_asg_45 = r2_score(y_test_delta_asg_45, predictions_delta_asg_45)

print(f"MSE_0: {mse_delta_asg_0}, R2_0: {r2_delta_asg_0}, MSE_45: {mse_delta_asg_45}, R2_45: {r2_delta_asg_45}")


MSE_0: 0.6339715961283588, R2_0: 0.19067335522449913, MSE_45: 0.35659811833468497, R2_45: 0.29629502337625724


In [148]:
# Feature importance from the Random Forest models
importances_delta_asg_0 = rf_model_delta_asg_0.feature_importances_
importances_delta_asg_45 = rf_model_delta_asg_45.feature_importances_

# Create a DataFrame to display feature importance
feature_importance_delta_asg_0 = pd.Series(importances_delta_asg_0, index=X.columns).sort_values(ascending=False)
feature_importance_delta_asg_45 = pd.Series(importances_delta_asg_45, index=X.columns).sort_values(ascending=False)

print(feature_importance_delta_asg_0)
print("")
print(feature_importance_delta_asg_45)


asg_0_pre     0.317582
asg_45_pre    0.237702
age           0.170815
MRD-1 3M      0.087457
挙筋機能 pre      0.086489
MRD-1 pre     0.074145
sex           0.014591
手術側           0.011219
const         0.000000
dtype: float64

asg_45_pre    0.499993
asg_0_pre     0.149344
age           0.144336
挙筋機能 pre      0.073416
MRD-1 pre     0.063851
MRD-1 3M      0.048353
sex           0.012439
手術側           0.008268
const         0.000000
dtype: float64


In [ ]:
from sklearn.tree import export_graphviz
import graphviz

# Extract one tree from the Random Forest model for Δasg_45
tree_example = rf_model_delta_asg_0.estimators_[0]

# Export the tree in DOT format
dot_data = export_graphviz(tree_example, out_file=None,
                           feature_names=X.columns,
                           filled=True, rounded=True,
                           special_characters=True)

# Generate a graph from DOT data
graph = graphviz.Source(dot_data)
graph

In [ ]:
from sklearn.tree import export_graphviz
import graphviz

# Extract one tree from the Random Forest model for Δasg_45
tree_example = rf_model_delta_asg_45.estimators_[0]

# Export the tree in DOT format
dot_data = export_graphviz(tree_example, out_file=None,
                           feature_names=X.columns,
                           filled=True, rounded=True,
                           special_characters=True)

# Generate a graph from DOT data
graph = graphviz.Source(dot_data)
graph
